name: Testing React Vite

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "18"

         - name: Install dependencies
           run: yarn install

         - name: Build
           run: yarn build

   test:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "18"

         - name: Install dependencies
           run: yarn install

         - name: Test
           run: yarn test

   deploy:
      runs-on: ubuntu-latest
      needs: [build, test]

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "18"

         - name: Intall vercel
           run: yarn global add vercel

         - name: Deploy to Vercel
           run: vercel --token ${{ secrets.VERCEL_TOKEN }} -y